services:

  jupyter:
      image: jupyter/base-notebook:latest
      environment:
        JUPYTER_ENABLE_LAB: "yes"
        GRANT_SUDO: "yes"
        PYTHONPATH: "/home/jovyan/work/src"
      user: root
      ports:
        - "8880:8888"
      volumes:
        - ./project:/home/jovyan/work
        - ./project/kaggle.json:/home/jovyan/.config/kaggle/kaggle.json
      command: >
        bash -c "
        chown jovyan /home/jovyan/.config/kaggle/kaggle.json &&
        chown 600 /home/jovyan/.config/kaggle/kaggle.json &&
        pip install -r /home/jovyan/work/config/requirements.txt &&
        start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
      restart: always
      depends_on:
        postgres:
          condition: service_healthy

  postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: students
      ports:
        - "5432:5432"
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U user"]
        interval: 10s
        timeout: 5s
        retries: 5
      restart: always