# Nom du workflow tel qu'il apparaîtra dans l'onglet "Actions" sur GitHub
name: Run Python Tests

# Déclenchement du workflow : ici à chaque push sur la branche 'main'
on:
  push:
    branches:
      - 'feature_test'

# Définition des jobs à exécuter
jobs:
  test:                       # Nom du job
    runs-on: ubuntu-latest    # Environnement d'exécution (machine Linux Ubuntu)

    # Liste des étapes du job
    steps:
      # Étape 1 : Récupérer le dépôt GitHub dans la machine virtuelle
      - name: Checkout repository
        uses: actions/checkout@v4   # Action officielle GitHub pour cloner le dépôt

      # Étape 2 : Installer Python dans l'environnement
      - name: Set up Python
        uses: actions/setup-python@v5  # Action officielle GitHub qui télécharge et installe Python
        with:
          python-version: '3.13'    # Version de Python à utiliser

      # Étape 3 : Installer les dépendances du projet
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip   # Mise à jour de pip
          pip install -r requirements.txt       # Installation des dépendances listées dans requirements.txt

      # Étape 4 : Lancer les tests automatisés avec pytest
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          pytest 
